### ISSUE TITLE
Side nav drawer slow/laggy to pull in over HomeFragment with many notes

### ISSUE THREAD

**Issue by icasdri** [icasdri/tuhi-android#2]
When sliding from the left, the side nav drawer is slow/laggy to pull in over the HomeFragment (with the notes list and SuperRecyclerView). The transition is not smooth, and seems to jitter in the middle. 

This seems to be correlated with how many notes the home fragment has -- with "a lot" of notes (~12 notes), it lags, with "not that many" notes (~3 notes), it's fine. 

Pull in over other fragments (only other one is DeletedFragment right now), is fine as well.

**Comment by nosduco** [comment]
Fixed in https://github.com/icasdri/tuhi-android/commit/74d163277d9d6655a211230a17e2bc01b25f50c5
